import React, { useState } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { Plus } from 'lucide-react';

const faqs = [
  {
    question: "How does the credit system work?",
    answer: "Each code generation or summary costs 1 credit. Free users get 15 credits on signup. Pro users get 1,000 monthly credits. If you run out, you can purchase top-ups via your dashboard."
  },
  {
    question: "Which programming languages are supported?",
    answer: "Omnicode AI supports over 20+ languages including JavaScript (React, Node.js), Python, Java, C++, Go, Rust, and SQL. We also support framework-specific generation for the MERN stack."
  },
  {
    question: "Who owns the code generated by Omnicode AI?",
    answer: "You do. All code generated through our platform is 100% yours to use, modify, and distribute, even for commercial projects. We don't claim any ownership."
  },
  {
    question: "Can I cancel my subscription at any time?",
    answer: "Yes, you can cancel your Pro plan at any time through the billing settings. You will retain access to your credits until the end of your current billing cycle."
  }
];

// Framer Motion Variants
const containerVariants = {
  hidden: { opacity: 0 },
  visible: {
    opacity: 1,
    transition: { staggerChildren: 0.1 },
  },
};

const itemVariants = {
  hidden: { opacity: 0, y: 20 },
  visible: { 
    opacity: 1, 
    y: 0,
    transition: { duration: 0.5, ease: "easeOut" }
  },
};

export default function FAQ() {
  const [openIndex, setOpenIndex] = useState(null);

  const toggleFAQ = (index) => {
    setOpenIndex(openIndex === index ? null : index);
  };

  return (
    // CHANGED: bg-white to bg-slate-950
    <section id="faq" className="py-24 bg-slate-950 relative overflow-hidden">
      
      {/* Background Glow */}
      <div className="absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2 w-[600px] h-[600px] bg-indigo-600/5 blur-[120px] rounded-full pointer-events-none" />

      <div className="max-w-3xl mx-auto px-6 relative z-10">
        
        {/* Header */}
        <motion.div 
          initial={{ opacity: 0, y: 20 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true, margin: "-100px" }}
          transition={{ duration: 0.6 }}
          className="text-center mb-16"
        >
          {/* CHANGED: text-slate-950 to text-white */}
          <h2 className="text-4xl font-[950] text-white mb-4 tracking-tight">
            Common Questions
          </h2>
          {/* CHANGED: text-slate-600 to text-slate-400 */}
          <p className="text-slate-400 font-medium text-lg">
            Everything you need to know about Omnicode AI.
          </p>
        </motion.div>

        {/* FAQ Accordion */}
        <motion.div 
          variants={containerVariants}
          initial="hidden"
          whileInView="visible"
          viewport={{ once: true, margin: "-50px" }}
          className="space-y-4"
        >
          {faqs.map((faq, i) => {
            const isOpen = openIndex === i;

            return (
              <motion.div 
                key={i} 
                variants={itemVariants}
                // CHANGED: Glassmorphism borders and backgrounds
                className={`border rounded-2xl overflow-hidden transition-all duration-300 backdrop-blur-xl ${
                  isOpen 
                    ? 'border-indigo-500/30 bg-indigo-500/10 shadow-[0_0_20px_rgba(99,102,241,0.1)]' 
                    : 'border-white/10 bg-white/5 hover:bg-white/10 hover:border-white/20'
                }`}
              >
                <button 
                  onClick={() => toggleFAQ(i)}
                  className="w-full flex items-center justify-between p-6 text-left outline-none focus-visible:ring-2 focus-visible:ring-indigo-500/50"
                >
                  {/* CHANGED: Text colors for contrast */}
                  <span className={`text-[17px] font-bold transition-colors ${isOpen ? 'text-indigo-300' : 'text-slate-200'}`}>
                    {faq.question}
                  </span>
                  
                  {/* Rotating Plus Icon */}
                  <motion.div 
                    animate={{ rotate: isOpen ? 45 : 0 }}
                    transition={{ duration: 0.3, ease: "easeInOut" }}
                    // CHANGED: Icon backgrounds
                    className={`flex-shrink-0 ml-4 p-1 rounded-full ${isOpen ? 'bg-indigo-500/20 text-indigo-400' : 'text-slate-400 bg-white/5'}`}
                  >
                    <Plus size={20} strokeWidth={2.5} />
                  </motion.div>
                </button>
                
                {/* Smooth Expand/Collapse Content */}
                <AnimatePresence initial={false}>
                  {isOpen && (
                    <motion.div
                      initial={{ height: 0, opacity: 0 }}
                      animate={{ height: "auto", opacity: 1 }}
                      exit={{ height: 0, opacity: 0 }}
                      transition={{ duration: 0.3, ease: [0.4, 0, 0.2, 1] }}
                    >
                      {/* CHANGED: Answer text color to slate-400 */}
                      <div className="px-6 pb-6 pt-2 text-slate-400 leading-relaxed font-medium">
                        {faq.answer}
                      </div>
                    </motion.div>
                  )}
                </AnimatePresence>
              </motion.div>
            );
          })}
        </motion.div>
      </div>
    </section>
  );
}